# Generated by Django 3.0.3 on 2020-02-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='phoneNo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
