# Generated by Django 3.0.3 on 2020-02-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='amount',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='username',
            field=models.CharField(max_length=7),
        ),
    ]
