# Generated by Django 3.0.3 on 2020-02-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20200205_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='date',
            new_name='dt',
        ),
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='time',
            new_name='tm',
        ),
    ]
