# Generated by Django 3.0.3 on 2020-02-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20200205_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='tm',
        ),
    ]
