# Generated by Django 3.0.3 on 2020-02-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20200205_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='date',
            field=models.DateField(default='2020-02-05'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='time',
            field=models.CharField(default='time', max_length=10),
        ),
    ]
