# Generated by Django 3.0.3 on 2020-02-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20200205_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
    ]
