# Generated by Django 3.0.3 on 2020-02-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_auto_20200205_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemindModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pay', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, max_length=100)),
                ('date', models.CharField(default='', max_length=10)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
