# Generated by Django 3.0.3 on 2020-02-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remindmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='account',
            field=models.CharField(default='3456128908', max_length=10),
        ),
    ]
