# Generated by Django 3.0.3 on 2020-02-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_assosiatemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='account',
            field=models.CharField(default='', max_length=10),
        ),
    ]
